# Generated by Django 4.2.30 on 2026-05-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("text", models.TextField()),
                ("image", models.ImageField(upload_to="news_uploads/")),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "ai_result",
                    models.CharField(
                        choices=[
                            ("REAL", "Real"),
                            ("FAKE", "Fake"),
                            ("SUSPICIOUS", "Suspicious"),
                        ],
                        default="SUSPICIOUS",
                        max_length=20,
                    ),
                ),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("text_similarity_score", models.FloatField(default=0.0)),
                ("trust_score", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REAL", "Real"),
                            ("FAKE", "Fake"),
                            ("SUSPICIOUS", "Suspicious"),
                        ],
                        default="SUSPICIOUS",
                        max_length=20,
                    ),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("QUEUED", "Queued"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
