# Generated by Django 4.2.30 on 2026-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsupload",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
