# Generated by Django 4.2.30 on 2026-05-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_newsupload_audit_and_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="newsupload",
            name="uploads_softdelete_idx",
        ),
        migrations.AlterField(
            model_name="newsupload",
            name="ai_result",
            field=models.CharField(
                choices=[
                    ("REAL", "Real photograph"),
                    ("AI_GEN", "AI-generated"),
                    ("UNCERTAIN", "Uncertain"),
                ],
                db_index=True,
                default="UNCERTAIN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsupload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="newsupload",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="newsupload",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("QUEUED", "Queued for review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                db_index=True,
                default="NONE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="newsupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("REAL", "Real photograph"),
                    ("AI_GEN", "AI-generated"),
                    ("UNCERTAIN", "Uncertain"),
                ],
                db_index=True,
                default="UNCERTAIN",
                max_length=20,
            ),
        ),
    ]
